twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        hour: '@App\Twig\HoursExtension'
        garage: '@App\Twig\ContactExtension'

when@test:
    twig:
        strict_variables: true
