vich_uploader:
    db_driver: orm

    metadata:
      type: attribute

    mappings:
      car_images:
        uri_prefix: /images/voitureOccasion
        upload_destination: '%kernel.project_dir%/public/images/voitureOccasion'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer