vich_uploader:
    db_driver: orm

    metadata:
      type: attribute

    mappings:
      category_image:
        uri_prefix: /images/voitureOccasion
        upload_destination: '%kernel.project_dir%/public/imgages/voitureOccasion'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer